# Generated by Django 2.2.12 on 2020-10-16 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200824_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=models.SET('deleted'), related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
