# Generated by Django 2.2.12 on 2020-10-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201025_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=models.SET('deleted'), related_name='listings', to='auctions.Category'),
        ),
    ]
