# Generated by Django 2.2.12 on 2020-10-25 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201025_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=models.SET('deleted'), related_name='winnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
