# Generated by Django 2.2.12 on 2020-11-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201025_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
