# Generated by Django 2.2.12 on 2020-11-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_price',
            new_name='currentBid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='image_url',
            new_name='imageURL',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='starting_price',
            new_name='startingBid',
        ),
    ]
