# Generated by Django 2.2.12 on 2020-11-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201104_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currentBid_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='startingBid_currency',
        ),
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
