# Generated by Django 2.2.12 on 2020-11-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201106_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currentBid',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), related_name='highestBid', to='auctions.Bid'),
        ),
    ]
