# Generated by Django 2.2.12 on 2020-11-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201111_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
