# Generated by Django 2.2.12 on 2020-11-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201111_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), related_name='listings', to='auctions.Category'),
        ),
    ]
