# Generated by Django 2.2.12 on 2020-11-14 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201111_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), related_name='winnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
