# Generated by Django 2.2.12 on 2020-11-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201118_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='startingPrice',
        ),
    ]
